### ISSUE TITLE
Recipe javax/addjaxbdependencies adds unnecessary jaxb dependency when Spring Boot is >= 2.2

### ISSUE THREAD

**Issue by Philzen** [openrewrite/rewrite-migrate-java#310] opened 2023-10-03 18:01 UTC
## What version of OpenRewrite are you using?

I am using

OpenRewrite v8.7.2 from the CLI

## How are you running OpenRewrite?

Using the CLI command directly from https://docs.openrewrite.org/recipes/java/migrate/javax/addjaxbdependencies:

```bash
mvn -U org.openrewrite.maven:rewrite-maven-plugin:run \
  -Drewrite.recipeArtifactCoordinates=org.openrewrite.recipe:rewrite-migrate-java:RELEASE \
  -Drewrite.activeRecipes=org.openrewrite.java.migrate.javax.AddJaxbDependencies
```

Actually, i discovered this running the [upgradetojava17](https://docs.openrewrite.org/recipes/java/migrate/upgradetojava17) recipe, but looking at the recipe tree the culprit is `javax/addjaxbdependencies`:

```terminal
[INFO] Running recipe(s)...
[WARNING] Changes have been made to pom.xml by:
[WARNING]     org.openrewrite.java.migrate.UpgradeToJava17
[WARNING]         org.openrewrite.java.migrate.Java8toJava11
[WARNING]             org.openrewrite.java.migrate.javax.AddJaxbDependencies
[WARNING]                 org.openrewrite.java.migrate.javax.AddJaxbRuntime: {runtime=glassfish}
[WARNING]                     org.openrewrite.java.migrate.javax.AddJaxbRuntime$AddJaxbRuntimeMaven
[WARNING]         org.openrewrite.java.migrate.JavaVersion17
[WARNING]             org.openrewrite.java.migrate.UpgradeJavaVersion: {version=17}
[WARNING] Please review and commit the results.
```

## What did you expect to see?

No change to this particular project's dependencies, as none of the main code, nor the tests is using any classes from `com.sun.xml.*`.

## What did you see instead?

It made the following addition to the POM:

```diff
             <groupId>org.springframework.boot</groupId>
             <artifactId>spring-boot-starter-web</artifactId>
         </dependency>
+        <dependency>
+            <groupId>org.glassfish.jaxb</groupId>
+            <artifactId>jaxb-runtime</artifactId>
+            <scope>test</scope>
+        </dependency>
 
         <dependency>
             <groupId>org.springframework.boot</groupId>
```

## What is the full stack trace of any errors you encountered?

<details><summary>Full maven CLI output</summary>
<code>

$ mvn -U org.openrewrite.maven:rewrite-maven-plugin:run \
  -Drewrite.recipeArtifactCoordinates=org.openrewrite.recipe:rewrite-migrate-java:RELEASE \
  -Drewrite.activeRecipes=org.openrewrite.java.migrate.UpgradeToJava17
[INFO] Scanning for projects...
Downloading from central: https://repo.maven.apache.org/maven2/org/openrewrite/maven/rewrite-maven-plugin/maven-metadata.xml
Downloaded from central: https://repo.maven.apache.org/maven2/org/openrewrite/maven/rewrite-maven-plugin/maven-metadata.xml (4.6 kB at 7.2 kB/s)
[INFO] 
[INFO] -------------------------< de.moovit.mcc:AMQP >-------------------------
[INFO] Building amqp 4.1.0.8
[INFO]   from pom.xml
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] >>> rewrite:5.7.1:run (default-cli) > process-test-classes @ AMQP >>>
[INFO] 
[INFO] --- build-helper:3.3.0:add-source (add-source) @ AMQP ---
[INFO] Source directory: /home/phil/prog/moovit/components/amqp/target/generated/src/main/java added.
[INFO] 
[INFO] --- openapi-generator:7.0.1:generate (default) @ AMQP ---
[INFO] Code generation is skipped because input was unchanged
[INFO] 
[INFO] --- resources:3.2.0:resources (default-resources) @ AMQP ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Using 'UTF-8' encoding to copy filtered properties files.
[INFO] Copying 2 resources
[INFO] 
[INFO] --- compiler:3.10.1:compile (default-compile) @ AMQP ---
[INFO] Compiling 2 source files to /home/phil/prog/moovit/components/amqp/target/classes
[INFO] 
[INFO] --- resources:3.2.0:testResources (default-testResources) @ AMQP ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Using 'UTF-8' encoding to copy filtered properties files.
[INFO] Copying 2 resources
[INFO] 
[INFO] --- compiler:3.10.1:testCompile (default-testCompile) @ AMQP ---
[INFO] Compiling 1 source file to /home/phil/prog/moovit/components/amqp/target/test-classes
[INFO] 
[INFO] <<< rewrite:5.7.1:run (default-cli) < process-test-classes @ AMQP <<<
[INFO] 
[INFO] 
[INFO] --- rewrite:5.7.1:run (default-cli) @ AMQP ---
[INFO] Using active recipe(s) [org.openrewrite.java.migrate.UpgradeToJava17]
[INFO] Using active styles(s) []
Downloading from central: https://repo.maven.apache.org/maven2/org/openrewrite/recipe/rewrite-migrate-java/maven-metadata.xml
Downloaded from central: https://repo.maven.apache.org/maven2/org/openrewrite/recipe/rewrite-migrate-java/maven-metadata.xml (2.0 kB at 15 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/openrewrite/recipe/rewrite-migrate-java/2.1.1/rewrite-migrate-java-2.1.1.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/openrewrite/recipe/rewrite-migrate-java/2.1.1/rewrite-migrate-java-2.1.1.pom (6.3 kB at 39 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/openrewrite/rewrite-bom/8.7.2/rewrite-bom-8.7.2.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/openrewrite/rewrite-bom/8.7.2/rewrite-bom-8.7.2.pom (5.6 kB at 136 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/openrewrite/rewrite-java/8.7.2/rewrite-java-8.7.2.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/openrewrite/rewrite-java/8.7.2/rewrite-java-8.7.2.pom (5.6 kB at 135 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/openrewrite/rewrite-core/8.7.2/rewrite-core-8.7.2.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/openrewrite/rewrite-core/8.7.2/rewrite-core-8.7.2.pom (5.1 kB at 131 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/openrewrite/rewrite-yaml/8.7.2/rewrite-yaml-8.7.2.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/openrewrite/rewrite-yaml/8.7.2/rewrite-yaml-8.7.2.pom (4.1 kB at 105 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/openrewrite/rewrite-xml/8.7.2/rewrite-xml-8.7.2.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/openrewrite/rewrite-xml/8.7.2/rewrite-xml-8.7.2.pom (3.9 kB at 101 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/xerial/snappy/snappy-java/1.1.10.5/snappy-java-1.1.10.5.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/xerial/snappy/snappy-java/1.1.10.5/snappy-java-1.1.10.5.pom (3.1 kB at 83 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/ow2/asm/asm/9.6/asm-9.6.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/ow2/asm/asm/9.6/asm-9.6.pom (2.4 kB at 55 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/ow2/asm/asm-util/9.6/asm-util-9.6.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/ow2/asm/asm-util/9.6/asm-util-9.6.pom (2.9 kB at 67 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/ow2/asm/asm-tree/9.6/asm-tree-9.6.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/ow2/asm/asm-tree/9.6/asm-tree-9.6.pom (2.6 kB at 60 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/ow2/asm/asm-analysis/9.6/asm-analysis-9.6.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/ow2/asm/asm-analysis/9.6/asm-analysis-9.6.pom (2.6 kB at 69 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/openrewrite/rewrite-maven/8.7.2/rewrite-maven-8.7.2.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/openrewrite/rewrite-maven/8.7.2/rewrite-maven-8.7.2.pom (5.7 kB at 136 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/openrewrite/rewrite-properties/8.7.2/rewrite-properties-8.7.2.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/openrewrite/rewrite-properties/8.7.2/rewrite-properties-8.7.2.pom (3.8 kB at 100 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/openrewrite/rewrite-gradle/8.7.2/rewrite-gradle-8.7.2.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/openrewrite/rewrite-gradle/8.7.2/rewrite-gradle-8.7.2.pom (4.3 kB at 120 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/openrewrite/rewrite-groovy/8.7.2/rewrite-groovy-8.7.2.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/openrewrite/rewrite-groovy/8.7.2/rewrite-groovy-8.7.2.pom (4.0 kB at 107 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/openrewrite/gradle/tooling/model/1.3.1/model-1.3.1.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/openrewrite/gradle/tooling/model/1.3.1/model-1.3.1.pom (3.4 kB at 93 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/openrewrite/recipe/rewrite-github-actions/2.0.6/rewrite-github-actions-2.0.6.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/openrewrite/recipe/rewrite-github-actions/2.0.6/rewrite-github-actions-2.0.6.pom (4.2 kB at 121 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/openrewrite/rewrite-yaml/8.7.1/rewrite-yaml-8.7.1.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/openrewrite/rewrite-yaml/8.7.1/rewrite-yaml-8.7.1.pom (4.1 kB at 108 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/openrewrite/rewrite-core/8.7.1/rewrite-core-8.7.1.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/openrewrite/rewrite-core/8.7.1/rewrite-core-8.7.1.pom (5.1 kB at 142 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/openrewrite/recipe/rewrite-java-dependencies/1.0.10/rewrite-java-dependencies-1.0.10.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/openrewrite/recipe/rewrite-java-dependencies/1.0.10/rewrite-java-dependencies-1.0.10.pom (5.4 kB at 139 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/openrewrite/rewrite-bom/8.7.1/rewrite-bom-8.7.1.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/openrewrite/rewrite-bom/8.7.1/rewrite-bom-8.7.1.pom (5.6 kB at 26 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/openrewrite/rewrite-maven/8.7.1/rewrite-maven-8.7.1.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/openrewrite/rewrite-maven/8.7.1/rewrite-maven-8.7.1.pom (5.7 kB at 150 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/openrewrite/rewrite-xml/8.7.1/rewrite-xml-8.7.1.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/openrewrite/rewrite-xml/8.7.1/rewrite-xml-8.7.1.pom (3.9 kB at 21 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/openrewrite/rewrite-java/8.7.1/rewrite-java-8.7.1.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/openrewrite/rewrite-java/8.7.1/rewrite-java-8.7.1.pom (5.6 kB at 142 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/openrewrite/rewrite-properties/8.7.1/rewrite-properties-8.7.1.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/openrewrite/rewrite-properties/8.7.1/rewrite-properties-8.7.1.pom (3.8 kB at 102 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/openrewrite/rewrite-gradle/8.7.1/rewrite-gradle-8.7.1.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/openrewrite/rewrite-gradle/8.7.1/rewrite-gradle-8.7.1.pom (4.3 kB at 116 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/openrewrite/rewrite-groovy/8.7.1/rewrite-groovy-8.7.1.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/openrewrite/rewrite-groovy/8.7.1/rewrite-groovy-8.7.1.pom (4.0 kB at 101 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/openrewrite/gradle/tooling/model/1.3.0/model-1.3.0.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/openrewrite/gradle/tooling/model/1.3.0/model-1.3.0.pom (3.4 kB at 84 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/openrewrite/rewrite-java-8/8.7.1/rewrite-java-8-8.7.1.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/openrewrite/rewrite-java-8/8.7.1/rewrite-java-8-8.7.1.pom (3.7 kB at 91 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/openrewrite/rewrite-java-11/8.7.1/rewrite-java-11-8.7.1.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/openrewrite/rewrite-java-11/8.7.1/rewrite-java-11-8.7.1.pom (4.1 kB at 114 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/openrewrite/rewrite-java-17/8.7.1/rewrite-java-17-8.7.1.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/openrewrite/rewrite-java-17/8.7.1/rewrite-java-17-8.7.1.pom (4.1 kB at 93 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/openrewrite/recipe/rewrite-static-analysis/1.0.8/rewrite-static-analysis-1.0.8.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/openrewrite/recipe/rewrite-static-analysis/1.0.8/rewrite-static-analysis-1.0.8.pom (4.4 kB at 120 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/openrewrite/rewrite-kotlin/1.4.13/rewrite-kotlin-1.4.13.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/openrewrite/rewrite-kotlin/1.4.13/rewrite-kotlin-1.4.13.pom (4.2 kB at 105 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/openrewrite/meta/rewrite-analysis/2.0.6/rewrite-analysis-2.0.6.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/openrewrite/meta/rewrite-analysis/2.0.6/rewrite-analysis-2.0.6.pom (4.6 kB at 102 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/openrewrite/rewrite-templating/1.3.1/rewrite-templating-1.3.1.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/openrewrite/rewrite-templating/1.3.1/rewrite-templating-1.3.1.pom (3.1 kB at 23 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/commons-io/commons-io/2.14.0/commons-io-2.14.0.pom
Downloaded from central: https://repo.maven.apache.org/maven2/commons-io/commons-io/2.14.0/commons-io-2.14.0.pom (20 kB at 333 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/commons/commons-parent/62/commons-parent-62.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/commons/commons-parent/62/commons-parent-62.pom (81 kB at 889 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/openrewrite/rewrite-java-8/8.7.2/rewrite-java-8-8.7.2.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/openrewrite/rewrite-java-8/8.7.2/rewrite-java-8-8.7.2.pom (3.7 kB at 66 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/openrewrite/rewrite-java-11/8.7.2/rewrite-java-11-8.7.2.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/openrewrite/rewrite-java-11/8.7.2/rewrite-java-11-8.7.2.pom (4.1 kB at 108 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/openrewrite/rewrite-java-17/8.7.2/rewrite-java-17-8.7.2.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/openrewrite/rewrite-java-17/8.7.2/rewrite-java-17-8.7.2.pom (4.1 kB at 117 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/openrewrite/recipe/rewrite-migrate-java/2.1.1/rewrite-migrate-java-2.1.1.jar
Downloaded from central: https://repo.maven.apache.org/maven2/org/openrewrite/recipe/rewrite-migrate-java/2.1.1/rewrite-migrate-java-2.1.1.jar (665 kB at 1.3 MB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/openrewrite/rewrite-java/8.7.2/rewrite-java-8.7.2.jar
Downloading from central: https://repo.maven.apache.org/maven2/org/xerial/snappy/snappy-java/1.1.10.5/snappy-java-1.1.10.5.jar
Downloading from central: https://repo.maven.apache.org/maven2/org/openrewrite/rewrite-xml/8.7.2/rewrite-xml-8.7.2.jar
Downloading from central: https://repo.maven.apache.org/maven2/org/openrewrite/rewrite-yaml/8.7.2/rewrite-yaml-8.7.2.jar
Downloading from central: https://repo.maven.apache.org/maven2/org/openrewrite/rewrite-core/8.7.2/rewrite-core-8.7.2.jar
Downloaded from central: https://repo.maven.apache.org/maven2/org/openrewrite/rewrite-xml/8.7.2/rewrite-xml-8.7.2.jar (220 kB at 677 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/ow2/asm/asm/9.6/asm-9.6.jar
Downloaded from central: https://repo.maven.apache.org/maven2/org/openrewrite/rewrite-yaml/8.7.2/rewrite-yaml-8.7.2.jar (236 kB at 642 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/ow2/asm/asm-util/9.6/asm-util-9.6.jar
Downloaded from central: https://repo.maven.apache.org/maven2/org/ow2/asm/asm/9.6/asm-9.6.jar (124 kB at 318 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/ow2/asm/asm-tree/9.6/asm-tree-9.6.jar
Downloaded from central: https://repo.maven.apache.org/maven2/org/ow2/asm/asm-tree/9.6/asm-tree-9.6.jar (52 kB at 115 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/ow2/asm/asm-analysis/9.6/asm-analysis-9.6.jar
Downloaded from central: https://repo.maven.apache.org/maven2/org/ow2/asm/asm-util/9.6/asm-util-9.6.jar (91 kB at 174 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/openrewrite/rewrite-maven/8.7.2/rewrite-maven-8.7.2.jar
Downloaded from central: https://repo.maven.apache.org/maven2/org/ow2/asm/asm-analysis/9.6/asm-analysis-9.6.jar (34 kB at 64 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/openrewrite/rewrite-properties/8.7.2/rewrite-properties-8.7.2.jar
Downloaded from central: https://repo.maven.apache.org/maven2/org/openrewrite/rewrite-properties/8.7.2/rewrite-properties-8.7.2.jar (53 kB at 84 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/openrewrite/rewrite-gradle/8.7.2/rewrite-gradle-8.7.2.jar
Downloaded from central: https://repo.maven.apache.org/maven2/org/openrewrite/rewrite-java/8.7.2/rewrite-java-8.7.2.jar (1.6 MB at 1.8 MB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/openrewrite/rewrite-groovy/8.7.2/rewrite-groovy-8.7.2.jar
Downloaded from central: https://repo.maven.apache.org/maven2/org/openrewrite/rewrite-groovy/8.7.2/rewrite-groovy-8.7.2.jar (174 kB at 175 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/openrewrite/recipe/rewrite-github-actions/2.0.6/rewrite-github-actions-2.0.6.jar
Downloaded from central: https://repo.maven.apache.org/maven2/org/openrewrite/recipe/rewrite-github-actions/2.0.6/rewrite-github-actions-2.0.6.jar (31 kB at 27 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/openrewrite/recipe/rewrite-java-dependencies/1.0.10/rewrite-java-dependencies-1.0.10.jar
Downloaded from central: https://repo.maven.apache.org/maven2/org/xerial/snappy/snappy-java/1.1.10.5/snappy-java-1.1.10.5.jar (2.3 MB at 1.9 MB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/openrewrite/recipe/rewrite-static-analysis/1.0.8/rewrite-static-analysis-1.0.8.jar
Downloaded from central: https://repo.maven.apache.org/maven2/org/openrewrite/rewrite-maven/8.7.2/rewrite-maven-8.7.2.jar (662 kB at 541 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/openrewrite/rewrite-kotlin/1.4.13/rewrite-kotlin-1.4.13.jar
Downloaded from central: https://repo.maven.apache.org/maven2/org/openrewrite/recipe/rewrite-java-dependencies/1.0.10/rewrite-java-dependencies-1.0.10.jar (259 kB at 193 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/openrewrite/meta/rewrite-analysis/2.0.6/rewrite-analysis-2.0.6.jar
Downloaded from central: https://repo.maven.apache.org/maven2/org/openrewrite/recipe/rewrite-static-analysis/1.0.8/rewrite-static-analysis-1.0.8.jar (741 kB at 471 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/openrewrite/gradle/tooling/model/1.3.1/model-1.3.1.jar
Downloaded from central: https://repo.maven.apache.org/maven2/org/openrewrite/meta/rewrite-analysis/2.0.6/rewrite-analysis-2.0.6.jar (430 kB at 268 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/openrewrite/rewrite-templating/1.3.1/rewrite-templating-1.3.1.jar
Downloaded from central: https://repo.maven.apache.org/maven2/org/openrewrite/gradle/tooling/model/1.3.1/model-1.3.1.jar (39 kB at 23 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/commons-io/commons-io/2.14.0/commons-io-2.14.0.jar
Downloaded from central: https://repo.maven.apache.org/maven2/org/openrewrite/rewrite-kotlin/1.4.13/rewrite-kotlin-1.4.13.jar (592 kB at 334 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/openrewrite/rewrite-java-8/8.7.2/rewrite-java-8-8.7.2.jar
Downloaded from central: https://repo.maven.apache.org/maven2/org/openrewrite/rewrite-templating/1.3.1/rewrite-templating-1.3.1.jar (97 kB at 54 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/openrewrite/rewrite-java-11/8.7.2/rewrite-java-11-8.7.2.jar
Downloaded from central: https://repo.maven.apache.org/maven2/org/openrewrite/rewrite-java-11/8.7.2/rewrite-java-11-8.7.2.jar (102 kB at 54 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/openrewrite/rewrite-java-17/8.7.2/rewrite-java-17-8.7.2.jar
Downloaded from central: https://repo.maven.apache.org/maven2/commons-io/commons-io/2.14.0/commons-io-2.14.0.jar (494 kB at 258 kB/s)
Downloaded from central: https://repo.maven.apache.org/maven2/org/openrewrite/rewrite-java-8/8.7.2/rewrite-java-8-8.7.2.jar (100 kB at 52 kB/s)
Downloaded from central: https://repo.maven.apache.org/maven2/org/openrewrite/rewrite-java-17/8.7.2/rewrite-java-17-8.7.2.jar (105 kB at 52 kB/s)
Downloaded from central: https://repo.maven.apache.org/maven2/org/openrewrite/rewrite-core/8.7.2/rewrite-core-8.7.2.jar (3.3 MB at 1.4 MB/s)
Downloaded from central: https://repo.maven.apache.org/maven2/org/openrewrite/rewrite-gradle/8.7.2/rewrite-gradle-8.7.2.jar (11 MB at 3.5 MB/s)
[INFO] Validating active recipes...
[INFO] Project [amqp] Resolving Poms...
[INFO] Project [amqp] Parsing source files
[INFO] Running recipe(s)...
[WARNING] Changes have been made to pom.xml by:
[WARNING]     org.openrewrite.java.migrate.UpgradeToJava17
[WARNING]         org.openrewrite.java.migrate.Java8toJava11
[WARNING]             org.openrewrite.java.migrate.javax.AddJaxbDependencies
[WARNING]                 org.openrewrite.java.migrate.javax.AddJaxbRuntime: {runtime=glassfish}
[WARNING]                     org.openrewrite.java.migrate.javax.AddJaxbRuntime$AddJaxbRuntimeMaven
[WARNING]         org.openrewrite.java.migrate.JavaVersion17
[WARNING]             org.openrewrite.java.migrate.UpgradeJavaVersion: {version=17}
[WARNING] Please review and commit the results.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  39.121 s
[INFO] Finished at: 2023-10-03T19:00:35+02:00
[INFO] ------------------------------------------------------------------------

</code>
</details> 

## Important Info

This does not happen when i run this recipe on exactly the same project using Spring Boot 2.1.x – only starting with Spring Boot 2.2.x this happens.

**Comment by Philzen** [comment] 2023-10-03 18:02
I do realize from the discussion over at https://github.com/openrewrite/rewrite-spring/issues/437#issuecomment-1742575058 that many of these bug reports never surface because most users tend to just go straight for latest Spring Boot versions and/or JAVA using the awesome recipes provided by OpenRewrite. No Really, i think it's awesome, it's a great support, companion and reassurance in the process – as i'm currently investigating how to migrate 14 projects from Java 8 with Spring Boot 2.1 to Java 17 with Spring Boot 3.x for one of my customers.

The reason i'm stumbling into these details is mainly b/c i'm taking one step at the time, being 

→ Upgrade to Java 11 LTS  
→ Upgrade Spring Boot to latest 2.x (as Java 17 wasn't officially supported before 2.5)  
→ Upgrade to 17 LTS  
→ Upgrade to Spring Boot 3.x (which requires Java 17)

**Comment by simonzn** [comment] 2023-12-20 10:41
We have the same issue when upgrading a Spring Boot 2.7.11 application to Spring Boot 3.2.0 using the org.openrewrite.java.spring.boot3.UpgradeSpringBoot_3_2 recipe:

```
WARNING] Changes have been made to pom.xml by:
[WARNING]     org.openrewrite.java.spring.boot3.UpgradeSpringBoot_3_2
[WARNING]         org.openrewrite.java.spring.boot3.UpgradeSpringBoot_3_1
[WARNING]             org.openrewrite.java.spring.boot3.UpgradeSpringBoot_3_0
[WARNING]                 org.openrewrite.java.spring.boot2.UpgradeSpringBoot_2_7
                              [...]
[WARNING]                 org.openrewrite.java.migrate.UpgradeToJava17
[WARNING]                     org.openrewrite.java.migrate.Java8toJava11
[WARNING]                         org.openrewrite.java.migrate.javax.AddJaxbDependencies
[WARNING]                             org.openrewrite.java.migrate.javax.AddJaxbRuntime: {runtime=glassfish}
[WARNING]                                 org.openrewrite.java.migrate.javax.AddJaxbRuntime$AddJaxbRuntimeMaven
```

**Comment by timtebeek** [comment] 2023-12-21 13:27
Hi both; this in indeed unfortunately confirmed and we're eyeing a fix. Not yet sure of the cause, but suspect that resolving transitive dependencies might play some part. We've seen the same issue for both Maven and Gradle projects.

**Comment by simonzn** [comment] 2023-12-21 13:40
FYI, but not sure if this is helpful at all: As a workaround I wrote a small recipe that simply removes the dependency again unless we import something from the bind API in our project. To test the recipe, I imported the Marshaller in one of our _test_ classes. This resulted in a change that added a duplicated dependency like

```
+        <dependency>
+            <groupId>org.glassfish.jaxb</groupId>
+            <artifactId>jaxb-runtime</artifactId>
+            <scope>test</scope>
+        </dependency>
+        <dependency>
+            <groupId>org.glassfish.jaxb</groupId>
+            <artifactId>jaxb-runtime</artifactId>
+            <scope>runtime</scope>
+        </dependency>
```

Maybe that's the reason why AddJaxbRuntime required another cycle, which war removed recently with c001403b3c62d161227ed31aae85372589dc5113

**Comment by timtebeek** [comment] 2023-12-21 13:45
@knutwannheden any insights or altternatives here after the removal of the extra cycle?

**Comment by timtebeek** [comment] 2023-12-27 13:25
Likely solved in https://github.com/openrewrite/rewrite-migrate-java/commit/b6215379d0de1d63bcd19de5952d5edd3073b21b

**Closed** 2023-12-27 13:27 UTC
Labels: bug
